export const container: string;
export const show: string;
export const label: string;
export const close: string;
export const inputText: string;
export const options: string;
export const button: string;
export const confirmButton: string;
export const cancelButton: string;
